In [11]:
# import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# import the training dataset
train_dataset = pd.read_csv('train/CleanedTrainData.csv')
# # grabbing certain columns (no Name, RescuerID, VideoAmt, Description, PetID, PhotoAmount)
X = train_dataset.iloc[:, :-1].values
y = train_dataset.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# # feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [12]:
# training the decision tree model on the training set
from sklearn.tree import DecisionTreeClassifier

classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [13]:
# predicting the test set results
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

[[4 4]
 [2 3]
 [4 4]
 ...
 [2 4]
 [2 3]
 [2 2]]


In [14]:
# making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[  0   3   7   8   6]
 [  5  83  80  39  42]
 [ 11  68 141  88  51]
 [  7  64 104  87  63]
 [  6  48  89  62 143]]


0.3478927203065134

In [15]:
import pickle

#Serializing the model
with open('trained_model.pkl', 'wb') as f:
    pickle.dump(classifier, f)

#De-Serializing the model
with open('trained_model.pkl', 'rb') as f:
    clf_loaded = pickle.load(f)
    

#Check the pickle file by inputing the variables
model = pickle.load(open('trained_model.pkl','rb'))
print(model)
# print(model.predict([[55, 18, 0, 1, 1, 1]]))

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')
